version: "3.8"
services:
  db:
    image: postgres:alpine
    container_name: db_docker_symfony
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      - ./dataset:/dataset
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    networks:
      - dev

  blackfire:
    image: blackfire/blackfire:2
    ports: [ "8307" ]
    environment:
      # Exposes BLACKFIRE_* environment variables from the host
      BLACKFIRE_LOG_LEVEL: 4
      BLACKFIRE_CLIENT_ID: "7fa1081c-f261-4454-9531-2df726365290"
      BLACKFIRE_CLIENT_TOKEN: "a9686d0ed4e3b90acee451092bdf451c5189f5f0eed09b4df99f598bd3e25b91"
      BLACKFIRE_SERVER_ID: "7a8cca5a-f647-4e8e-861d-4a3d8bc919b1"
      BLACKFIRE_SERVER_TOKEN: "f1d4dfd878a11a0c6b41767a17d5faf47f3de2554297183238006f455ed7525a"

  www:
    build: php
    container_name: www_docker_symfony
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev
    links:
      - blackfire
  blackfire:
    image: blackfire/blackfire:2
    ports:
      - 8707:8707
    environment:
      # Exposes BLACKFIRE_* environment variables from the host
      BLACKFIRE_LOG_LEVEL: 4
      BLACKFIRE_CLIENT_ID: "7a0b22d2-8137-495f-be27-19de102ae8ee"
      BLACKFIRE_CLIENT_TOKEN: "206b0d67ced9bfc5ee1e99f51798839801c90b29c4a0e775e772084484b002e0"
      BLACKFIRE_SERVER_ID: "010dca3b-b106-4c2f-b1bc-677116255071"
      BLACKFIRE_SERVER_TOKEN: "75a2ec81dc414ef938fc177cf1e5207aedb97467b62fef847e1fb38bca23abce"
    networks:
      - dev
networks:
  dev:

volumes:
  db-data:
