version: "3.8"
services:
  db:
    image: postgres:alpine
    container_name: db_symfony
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      - ./dataset:/dataset
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    networks:
      - dev
  www:
    build: php
    container_name: www_symfony
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev
    links:
      - blackfire

  blackfire:
    container_name: blackfire_perf
    image: blackfire/blackfire:2
    ports:
      - 8307:8307
    environment:
      # Exposes BLACKFIRE_* environment variables from the host
      BLACKFIRE_LOG_LEVEL: 4
      BLACKFIRE_CLIENT_ID: "7fa1081c-f261-4454-9531-2df726365290"
      BLACKFIRE_CLIENT_TOKEN: "a9686d0ed4e3b90acee451092bdf451c5189f5f0eed09b4df99f598bd3e25b91"
      BLACKFIRE_SERVER_ID: "7a8cca5a-f647-4e8e-861d-4a3d8bc919b1"
      BLACKFIRE_SERVER_TOKEN: "f1d4dfd878a11a0c6b41767a17d5faf47f3de2554297183238006f455ed7525a"
    networks:
      - dev


  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
      - dev
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./k6/grafana:/etc/grafana/provisioning/

  k6:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./k6/scripts:/scripts

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - node-exporter:node-exporter
    networks:
      - dev

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - dev
    deploy:
      mode: global

networks:
  dev:
  k6:
  grafana:

volumes:
  db-data: